# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-05 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type1', models.TextField()),
                ('type2', models.TextField()),
                ('total_stats', models.IntegerField()),
                ('generation', models.IntegerField()),
                ('is_legendary', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id', 'total_stats'],
            },
        ),
    ]
